FROM php:8.4-fpm-alpine

RUN apk add --no-cache \
    bash \
    mc \
    # telnet
    busybox-extras

RUN curl -sS https://getcomposer.org/installer -o composer-setup.php
RUN php composer-setup.php --install-dir=/usr/local/bin --filename=composer